language: node_js
node_js:
  - 'node'
  - '6'
  - '4'
addons:
  code_climate:
    repo_token: e67e9cf111577cd34fd63384711c738230d8c2eb13342b5619a821dffb162634
notifications:
  slack: feathersjs:T4tvpJFt27wJZABjLSg5OqMv
  email: false
before_script:
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < coverage/lcov.info